### PR TITLE
fix(middleware): redirect after refreshing token

### LINKED ISSUE #71: implement redirecting to `/profile` after refreshing token

### PR DESCRIPTION
**Pull request by Mnigos**
closes #71

### CODE REVIEW

File: src/middleware.ts [hunk 1]
```diff
@@ -1,19 +1,31 @@
...
+    .then(() => true)
+
+  if (!refreshToken || isLoggedIn) return NextResponse.next()
+
+  const { accessToken: refreshedAccesToken } = await getRefresh(refreshToken)
 
   response.cookies.set({
     name: ACCESS_TOKEN,
-    value: accessToken,
+    value: refreshedAccesToken,
```
Comment (Iqro-dev) [inline src/middleware.ts:28]: Change 'Acces' to 'Access'

**Review by Iqro-dev — APPROVED** [review]
